name: Publish Docker image

on:
  workflow_dispatch:

env:
  TEST_TAG: user/app:test

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          build-args: |
            SP_VERSION=1
          file: ./kylin_v10.sys.Dockerfile
          push: true
          tags: hxsoong/kylin:v10-sp1
