name: Publish Kylin V10 Docker image

on:
  workflow_dispatch:
    inputs:
      sp_ver:
        description: 'SP version'
        required: true
        type: choice
        options:
          - all
          - sp1
          - sp2
          - sp3
          - sp3-2403
      push:
        description: 'Push to Docker Hub'
        type: boolean

jobs:
  setup:
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          if [[ "${{ inputs.sp_ver }}" == "all" ]]; then
            echo "matrix=[{\"sp_ver\":\"sp1\"},{\"sp_ver\":\"sp2\"},{\"sp_ver\":\"sp3\"},{\"sp_ver\":\"sp3-2403\"}]" >> $GITHUB_OUTPUT
          else
            echo "matrix=[{\"sp_ver\":\"${{inputs.sp_ver}}\"}]" >> $GITHUB_OUTPUT
          fi
  build:
    needs: [setup]
    strategy:
      matrix:
        include: ${{ fromJSON(needs.setup.outputs.matrix) }}

    name: Build and push
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          build-args: |
            SP_VERSION=${{ matrix.sp_ver }}
          file: ./kylin_v10.sys.Dockerfile
          push: ${{ inputs.push }}
          tags: ${{ vars.DOCKER_USERNAME }}/kylin:v10-${{ matrix.sp_ver }}
